[package]
name = "gen_random_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gen_random_proc_macro = { path = "../gen_random_proc_macro" }
gen_random = { path = "../gen_random" }
rand = "0.8"
